#!/bin/bash

function virsh { command virsh "$@" | tail -n +3; }
function foreach { xargs --no-run-if-empty -n 1 "$@"; }

virsh list --all | awk '{print $2}' | foreach virsh destroy
virsh list --all | awk '{print $2}' | foreach virsh undefine

virsh net-list --all | awk '{print $1}' | foreach virsh net-destroy
virsh net-list --all | awk '{print $1}' | foreach virsh net-undefine

