#!/bin/bash

function virsh { command virsh "$@" |grev -v "jenkins-"|awk 'NR>2 && $0!=""'; }
function foreach { xargs --no-run-if-empty -n 1 "$@"; }
function column { awk "{print \$$1}"; }

virsh list --all | column 2 | foreach virsh destroy
virsh list --all | column 2 | while read nodeid; do
  virsh snapshot-list $nodeid | column 1 | foreach virsh snapshot-delete $nodeid
  virsh undefine $nodeid
done

virsh net-list --all | column 1 | foreach virsh net-destroy
virsh net-list --all | column 1 | foreach virsh net-undefine

