default[:nailgun][:root] = "/opt/nailgun"
default[:nailgun][:group] = "nailgun"
default[:nailgun][:user] = "nailgun"
default[:nailgun][:venv] = "/opt/nailgun-venv"
default[:nailgun][:python] = "/opt/nailgun-venv/bin/python"
default[:nailgun][:pip] = "/opt/nailgun-venv/bin/pip"
