#!/bin/sh -e

PREREQS="udev"

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

RULES=80-net-name-slot.rules
if   [ -e /etc/udev/rules.d/$RULES ]; then
  cp -p /etc/udev/rules.d/$RULES $DESTDIR/lib/udev/rules.d/
elif [ -e /lib/udev/rules.d/$RULES ]; then
  cp -p /lib/udev/rules.d/$RULES $DESTDIR/lib/udev/rules.d/
fi
