#!/bin/sh

echo "Creating test file"
touch /home/test_file

echo "Creating volume mount script on instance"
echo "#!/bin/sh\nsudo /usr/sbin/mkfs.ext4 /dev/vdb\nsudo mount /dev/vdb /mnt" | tee /home/mount_volume.sh
chmod 777 /home/mount_volume.sh

echo -e "test\ntest" | passwd cirros
