#!/usr/bin/env python
#
#    Copyright 2014 Mirantis, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

# This script is supposed to be executed only during the upgrade of
# fuel-main package. Script will merge values added manually
# to implement "multiple cluster networks" with current astute
# settings and will print result to stdout.
#
# It will work only if dnsmasq.template was modified stictly according
# to documentation and modified lines matches pattern:
# dhcp-range=<name>,<start-IP-addr>,<end-IP-addr>,<netmask>,[<leasetime>]
# dhcp-option=net:<name>,option:router,<IP-addr-of-gateway>
# dhcp-boot=net:<name>,pxelinux.0,boothost,<Fuel-Master-IP-addr>
#
# Starting from 7.0 we will handle this feature by puppet manifests
# parsing section EXTRA_ADMIN_NETWORKS from astute.yaml

from collections import defaultdict
import yaml
import re
import sys


# This nets autogenerated by puppet according to networking settings
# of admin network. We will ignore them.
ignored_nets = ['6', 'internal']
nets = defaultdict(dict)

for line in sys.stdin:
    if re.match('[^#]*=[^#*]', line):
        item = re.split('(=|#)', line)
        name = re.split(',', item[2].strip())[0]
        value = re.split(',', item[2].strip())[1:]
        if item[0] in ['dhcp-option', 'dhcp-boot']:
            try:
                name = re.split(':', name)[1]
            except:
                continue
            if name in ignored_nets:
                continue
        if item[0] == 'dhcp-range':
            if name in ignored_nets:
                continue
            nets[name].update({'dhcp_pool_start': value[0]})
            nets[name].update({'dhcp_pool_end': value[1]})
            nets[name].update({'netmask': value[2]})
        if item[0] == 'dhcp-option':
            nets[name].update({'dhcp_gateway': value[1]})
        if item[0] == 'dhcp-boot':
            nets[name].update({'ipaddress': value[2]})

###write networks from dnsmasq to astute
astute = yaml.load(open('/etc/fuel/astute.yaml'))
astute['EXTRA_ADMIN_NETWORKS'] = {}
for net in nets:
    astute['EXTRA_ADMIN_NETWORKS'][net] = nets[net]

print yaml.dump(astute, default_flow_style=False)
