- job:
    name: fuel.manage_environment
    description: "This job is controlled by job builder. All manual changes will be rewritten on next re-build. Please update job config in fuel-main repo"
    logrotate:
      daysToKeep: -1
      numToKeep: 50
      artifactDaysToKeep: -1
      artifactNumToKeep: -1
    project-type: freestyle
    defaults: global
    disabled: false
    concurrent: true
    parameters:
      - string:
          name: ENV_NAME
          default: default_environment
          description:
      - string:
          name: iso_path
          default: "/home/jenkins/workspace/fuelweb_test.parent/product/build/iso/fuelweb-centos-6.4-x86_64.iso"
          description: "Specify this value manually in case you want to avoid make ISO step. Please use absolute path for this. Example /home/jenkins/workspace/fuelweb_test.integration.by_branch/product/build/iso/fuelweb-centos-6.4-x86_64.iso\
                      \n
                      \nBy default latest ISO from nightly test run will be used"
      - node:
          name:
          description:
          allowed-slaves:
            - srv07-srt
          default-slaves:
            - srv08-srt
          trigger-condition: disallow-multi-node

    scm:
     - git:
        url: https://github.com/stackforge/fuel-main.git
        refspec:
        name:
        choosing-strategy: default
        skip-tag: false
        wipe-workspace: false
        branches:
         - "origin/master"

    builders:
    - shell: "bash $JENKINS_HOME/fuel-main/utils/jenkins/fuel-ci/git-prep.sh\
            \n\
            \nbash $JENKINS_HOME/fuel-main/utils/jenkins/fuel-ci/jenkins-product/scripts/fuel.manage_environment.sh"

    publishers:
      - description-setter:
          regexp: "admin_node_ip='(admin node ip:\\d+\\.\\d+\\.\\d+\\.\\d+)"
      - email-ext:
          recipients: $DEFAULT_RECIPIENTS
          reply-to: $DEFAULT_REPLYTO
          subject: $DEFAULT_SUBJECT
          body: $DEFAULT_CONTENT
          failure: true
          success: true
          send-to:
            - requestor
