#! /bin/bash
#
# setup-bootdev       Setup necessary network interface to DHCP
#
# chkconfig: 2345 05 90
# description: Setup necessary network interface to DHCP.
#
### BEGIN INIT INFO
# Provides: $(setup-bootdev)
# Short-Description: Setup necessary network interface to DHCP
# Description: Setup necessary network interface to DHCP
### END INIT INFO

# Source function library.
. /etc/init.d/functions

# See how we were called.
rc=0
case "$1" in
  start)
    /usr/bin/setup-bootdev || rc=$?
    action $"Update network interfaces settings: " [ $rc -eq 0 ]
  ;;
  *)
    rc=0
  ;;
esac

exit $rc
